### ISSUE TITLE
"Invalid Date" when hovering over calendar

### ISSUE THREAD

**Issue by pta2002** [ludumdare/ludumdare#314]
![2016-11-29_22-32-12](https://cloud.githubusercontent.com/assets/7443916/20731783/be201486-b683-11e6-9447-4e19abf9734e.png)

**Comment by povrazor** [comment]
What browser?

**Comment by joaolucasbig** [comment]
I'm running on Chrome. Dont get this error here.

**Comment by pta2002** [comment]
It's Firefox. Might see if I can fix it when I get home

**Comment by povrazor** [comment]
Confirmed. I also see it in Firefox.

**Comment by StormBurpee** [comment]
Rather than displaying Invalid Date, the calendar appears to be a month ahead for me - it's showing January dates, rather than December.

**Comment by joaolucasbig** [comment]
Confirmed the @StormBurpee comment: The calendar is in fact a month ahead.
![screenshot_2](https://cloud.githubusercontent.com/assets/5459797/20835293/e64dd0b6-b880-11e6-9e7d-2fae7f56bd45.jpg)

**Comment by pta2002** [comment]
Huh. They are probably related.

**Comment by StormBurpee** [comment]
I think it's to do with the fact that Months are represented from 0-11 in JavaScript. In the calendar.js file (Under src/components/sidebar-calendar)
At the begging of the file PoV mentions this, and adds 1 to make it easier to read through the development. 

> let thisMonth = today.getMonth()+1;
let thisYear = today.getFullYear();
		

> /* Months and Weeks start at 0. Years and Days start at 1. Using 0th day is like -1 */
> let monthEndsOn = new Date(today.getFullYear(), today.getMonth()+1, 0).getDate();
> let nextDay = today.getDate() - today.getDay();

However, later on when the calendar is rendering, it calls the Generate Rows function,
Where he creates another Date variable off of this, (where it's still +1)

> props.title = col.month+"-"+col.day+"-"+col.year;
> if ( window.Intl ) {
> 	// http://stackoverflow.com/a/18648314/5678759
> 	let objDate = new Date(props.title);
> 	props.title = objDate.toLocaleString("en-us", {month:"long", day:"numeric", year:"numeric"});
> }

in the props.title if you subtract 1 from col.month, this should fix the issue. As javascript will parse 12 as 0, as it is 1 over the maximum (11). Therefore, 0 == January

**Comment by pta2002** [comment]
Alright then, that should also fix the Firefox issue (since 12 wouldn't be
a valid month)

**Comment by povrazor** [comment]
Unfortunately it does not appear to fix the Firefox problem. But yes, chrome is fixed.

**Comment by StormBurpee** [comment]
I guess I'll download firefox and take a look ;)

**Comment by povrazor** [comment]
This (and the google fix) are now live on the main server.

**Comment by povrazor** [comment]
This should now be fixed.
